# Generated by Django 3.0.6 on 2023-03-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('row_status', models.BooleanField()),
                ('salary_id', models.CharField(blank=True, max_length=32, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('result', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mailhistory',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('row_status', models.BooleanField()),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('position', models.CharField(blank=True, max_length=32, null=True)),
                ('bank_number', models.CharField(blank=True, max_length=32, null=True)),
                ('base_pay', models.CharField(blank=True, max_length=10, null=True)),
                ('seniority_pay', models.CharField(blank=True, max_length=10, null=True)),
                ('title_pay', models.CharField(blank=True, max_length=10, null=True)),
                ('academic_pay', models.CharField(blank=True, max_length=10, null=True)),
                ('assessment_bonus', models.CharField(blank=True, max_length=10, null=True)),
                ('housing_supplement', models.CharField(blank=True, max_length=10, null=True)),
                ('total_pay', models.CharField(blank=True, max_length=10, null=True)),
                ('pension', models.CharField(blank=True, max_length=10, null=True)),
                ('medical_insurance', models.CharField(blank=True, max_length=10, null=True)),
                ('unemployment', models.CharField(blank=True, max_length=10, null=True)),
                ('accumulation_fund', models.CharField(blank=True, max_length=10, null=True)),
                ('income_tax', models.CharField(blank=True, max_length=10, null=True)),
                ('union_fee', models.CharField(blank=True, max_length=10, null=True)),
                ('total_deduction', models.CharField(blank=True, max_length=10, null=True)),
                ('paidin_amount', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('email_address', models.CharField(blank=True, max_length=32, null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'salary',
            },
        ),
    ]
