# Generated by Django 3.0.6 on 2023-03-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaapp', '0002_auto_20230310_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cookie',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
