# Generated by Django 3.0.6 on 2023-03-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaapp', '0003_user_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_password',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
